#%RAML 1.0
title: timeapi

/time:
  get:
    displayName: To know the Time
    responses:
      200:
        body:
          application/json:
            example:
              {
                07:30:45
              }
        